language: python
install:
- pip install pytest
- pip install geojson
- pip install forked-path
- npm install -g geojson-merge
before_script:
- mv class-pins.topojson class-pins
- echo "I found new files, combining and pushing now!"
- geojson-merge *.topojson class-pins > class-pins.topojson
script: py.test
deploy:
  skip_cleanup: true
  provider: script
  script: bash -x deploy.sh
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_402c72cb72db_key -iv $encrypted_402c72cb72db_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
